name: Deploy to Amazon ECS

on:
  push:
    branches: ["main"]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22.12.0]

    steps:
      - name: Checkout Branch
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Cache node_modules
        uses: actions/cache@v2
        id: node_modules-cache
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-node_modules-${{ hashFiles('**/package-lock.json') }}

      - name: Install pnpm
        if: steps.node_modules-cache.outputs.cache-hit == ''
        run: npm install -g pnpm

      - name: Install pnpm
        run: pnpm i

      - name: Build
        run: npm run build

      - name: Make Directory for deliver
        run: mkdir deploy-kakao

      - name: Make frontend.tar.gz
        run: |
          sudo timedatectl set-timezone Asia/Seoul
          tar cvfPz ./deploy-kakao/frontend_`date "+%Y%m%d%H%M"`.tar.gz --exclude=./deploy-kakao .

      - name: Extract Env From Branch
        run: |
          BRANCH=${GITHUB_REF#refs/heads/}
          echo "env=$(echo ${BRANCH})" >> $GITHUB_OUTPUT
        id: branch

      - name: Remove Existing Tar Files And Upload Tar File to Kakao Cloud
        env:
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_USER: ${{ secrets.EC2_USER }}
          EC2_SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
        run: |
          echo "${EC2_SSH_PRIVATE_KEY}" | tr -d '\r' > private_key.pem
          chmod 600 private_key.pem

          # SSH 디렉터리 생성 및 호스트 키 추가
          # mkdir -p ~/.ssh
          # touch ~/.ssh/known_hosts
          # ssh-keygen -R ${EC2_HOST} || true
          # ssh-keyscan -H ${EC2_HOST} >> ~/.ssh/known_hosts

          # 서버에 있는 이전 파일 제거
          ssh -i private_key.pem ${EC2_USER}@${EC2_HOST} "/bin/rm -rf /home/${EC2_USER}/ssm-frontend-server/*"

          # 새 TAR 파일 업로드
          scp -i private_key.pem ./deploy-kakao/frontend_*.tar.gz ${EC2_USER}@${EC2_HOST}:/home/${EC2_USER}/ssm-frontend-server/

      - name: Restart PM2 using SSH action
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          script: |
            /home/${{ secrets.EC2_USER }}/script/deploy_frontend_prod.sh
