name: Deploy to Amazon ECS

on:
  push:
    branches: ["main"]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22.12.0]

    steps:
      - name: Checkout Branch
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Cache node_modules
        uses: actions/cache@v2
        id: node_modules-cache
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-node_modules-${{ hashFiles('**/package-lock.json') }}

      - name: npm install -g pnpm
        run: npm install -g pnpm

      - name: Install pnpm
        run: pnpm i

      - name: Build
        run: pnpm run build

      - name: Make Directory for deliver
        run: mkdir deploy-kakao

      - name: Make frontend.tar.gz
        run: |
          sudo timedatectl set-timezone Asia/Seoul
          tar cvfPz ./deploy-kakao/frontend_`date "+%Y%m%d%H%M"`.tar.gz --exclude=./deploy-kakao .

      - name: Extract Env From Branch
        run: |
          BRANCH=${GITHUB_REF#refs/heads/}
          echo "env=$(echo ${BRANCH})" >> $GITHUB_OUTPUT
        id: branch

      - name: Upload Tar File
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          source: ./deploy-kakao/frontend_*.tar.gz
          target: /home/${{ secrets.EC2_USER }}/blog/
